import { useCallback, useEffect, useMemo, useState } from "react";
import { mockAlerts, mockEvents, mockGeofences, mockRoutePerformance, mockVehicles, reportSummary, STATUS } from "../data/mockTrackingData";
import { createSimulationEvent, simulateVehicleTick } from "../utils/trackingSimulation";

const statusStyles={Active:"bg-green-100 text-green-800 border-green-200",Idle:"bg-amber-100 text-amber-800 border-amber-200","In Maintenance":"bg-purple-100 text-purple-800 border-purple-200",Delayed:"bg-red-100 text-red-800 border-red-200",Offline:"bg-slate-200 text-slate-700 border-slate-300","Returning To Base":"bg-blue-100 text-blue-800 border-blue-200"};
const statusColor={Active:"#15803D",Idle:"#B45309","In Maintenance":"#7E22CE",Delayed:"#B91C1C",Offline:"#475569","Returning To Base":"#0F2E66"};
const time=(d)=>new Date(d).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});
const dateTime=(d)=>new Date(d).toLocaleString([], {month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});
const unique=(items,key)=>[...new Set(items.map((item)=>item[key]))];

function StatusBadge({status}){return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-bold ${statusStyles[status]||statusStyles.Offline}`}>{status}</span>}
function Meter({value,tone="bg-brand-gold"}){return <div className="h-2 rounded-full bg-slate-200"><div className={`h-2 rounded-full ${tone}`} style={{width:`${Math.max(0,Math.min(100,value))}%`}} /></div>}

export default function Tracking(){
  const [vehicles,setVehicles]=useState(mockVehicles); const [alerts,setAlerts]=useState(mockAlerts); const [events,setEvents]=useState(mockEvents);
  const [selectedId,setSelectedId]=useState(mockVehicles[0].id); const [running,setRunning]=useState(false); const [speed,setSpeed]=useState(1); const [lastRefresh,setLastRefresh]=useState(new Date());
  const [search,setSearch]=useState(""); const [filters,setFilters]=useState({status:"All",type:"All",branch:"All",priority:"All",maintenance:"All"});
  const [toggles,setToggles]=useState({active:true,idle:true,offline:true,maintenance:true,delayed:true,routes:true,geofences:true,alerts:true,traffic:true});
  const selected=vehicles.find((v)=>v.id===selectedId);
  const tick=useCallback(()=>{setVehicles((current)=>{const next=simulateVehicleTick(current,speed); setEvents((e)=>[createSimulationEvent(next),...e].slice(0,60)); return next;}); setLastRefresh(new Date());},[speed]);
  useEffect(()=>{if(!running)return undefined; const id=setInterval(tick, Math.max(1200,4200/speed)); return()=>clearInterval(id);},[running,speed,tick]);
  const filtered=useMemo(()=>vehicles.filter((v)=>{
    const s=search.toLowerCase(); const visible=(v.status===STATUS.ACTIVE&&toggles.active)||(v.status===STATUS.IDLE&&toggles.idle)||(v.status===STATUS.OFFLINE&&toggles.offline)||(v.status===STATUS.MAINTENANCE&&toggles.maintenance)||(v.status===STATUS.DELAYED&&toggles.delayed)||v.status===STATUS.RETURNING;
    return visible && [v.vehicleName,v.driverName,v.plateNumber,v.currentLocationName,v.routeName,v.status].join(" ").toLowerCase().includes(s) && (filters.status==="All"||v.status===filters.status) && (filters.type==="All"||v.vehicleType===filters.type) && (filters.branch==="All"||v.assignedBranch===filters.branch) && (filters.priority==="All"||v.priority===filters.priority) && (filters.maintenance==="All"||(filters.maintenance==="Due"?v.maintenanceDue:!v.maintenanceDue));
  }),[vehicles,search,filters,toggles]);
  const openAlerts=alerts.filter((a)=>a.status==="Open");
  const kpis=[ ["Total Vehicles",vehicles.length,"🚚"],["Active Vehicles",vehicles.filter(v=>v.status===STATUS.ACTIVE).length,"🟢"],["Idle Vehicles",vehicles.filter(v=>v.status===STATUS.IDLE).length,"🟡"],["Delayed Vehicles",vehicles.filter(v=>v.status===STATUS.DELAYED).length,"🔴"],["Offline Vehicles",vehicles.filter(v=>v.status===STATUS.OFFLINE).length,"⚫"],["Average Speed",`${Math.round(vehicles.reduce((a,v)=>a+v.speedKmh,0)/vehicles.length)} km/h`,"⚡"],["Average Fuel Level",`${Math.round(vehicles.reduce((a,v)=>a+v.fuelLevel,0)/vehicles.length)}%`,"⛽"],["Deliveries Completed Today",vehicles.reduce((a,v)=>a+v.completedDeliveryCount,0),"📦"],["Open Alerts",openAlerts.length,"🚨"],["Vehicles Due For Maintenance",vehicles.filter(v=>v.maintenanceDue).length,"🛠️"] ];
  const reset=()=>{setVehicles(mockVehicles);setAlerts(mockAlerts);setEvents(mockEvents);setSelectedId(mockVehicles[0].id);setRunning(false);setLastRefresh(new Date());};
  return <div className="app-shell"><div className="app-container space-y-6">
    <section className="page-header flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">Live Tracking</p><h1 className="page-title">Live Vehicle Tracking</h1><p className="page-description">Monitor JD Carriers fleet activity across Saint Lucia in real time using mock vehicle telemetry.</p><p className="mt-3 text-sm font-semibold text-brand-slate">Last refresh: {lastRefresh.toLocaleTimeString()} • {running?"Simulation running":"Simulation paused"}</p></div><div className="rounded-2xl bg-brand-deep px-4 py-3 text-sm font-bold text-white">Saint Lucia Operations Control Center</div></section>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{kpis.map(([label,value,icon])=><div key={label} className="card-pad"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase text-brand-slate">{label}</p><span>{icon}</span></div><p className="mt-2 text-2xl font-extrabold text-brand-deep">{value}</p></div>)}</div>
    <section className="card-pad"><div className="grid gap-3 lg:grid-cols-4"><button className="btn-success" onClick={()=>setRunning(true)}>▶ Start Live Simulation</button><button className="btn-secondary" onClick={()=>setRunning(false)}>⏸ Pause Simulation</button><button className="btn-warning" onClick={reset}>↺ Reset Simulation</button><button className="btn-primary" onClick={tick}>⟳ Refresh Positions</button></div><div className="mt-4 flex flex-wrap gap-3"><select className="form-control max-w-32" value={speed} onChange={(e)=>setSpeed(Number(e.target.value))}>{[1,2,5,10].map(v=><option key={v} value={v}>{v}x speed</option>)}</select>{Object.keys(toggles).map(k=><label key={k} className="inline-flex items-center gap-2 rounded-xl bg-brand-soft px-3 py-2 text-sm font-semibold text-brand-deep"><input type="checkbox" checked={toggles[k]} onChange={()=>setToggles({...toggles,[k]:!toggles[k]})}/> Show {k}</label>)}</div></section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]"><TrackingMap vehicles={filtered} selectedId={selectedId} onSelect={setSelectedId} showRoutes={toggles.routes} showGeofences={toggles.geofences}/><DetailPanel vehicle={selected}/></div>
    <section className="card-pad"><h2 className="text-lg font-extrabold text-brand-deep">Fleet Filters</h2><div className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-6"><input className="form-control" placeholder="Search vehicle, driver, plate, route..." value={search} onChange={e=>setSearch(e.target.value)}/><Filter label="status" values={unique(vehicles,"status")} filters={filters} setFilters={setFilters}/><Filter label="type" keyName="type" values={unique(vehicles,"vehicleType")} filters={filters} setFilters={setFilters}/><Filter label="branch" values={unique(vehicles,"assignedBranch")} filters={filters} setFilters={setFilters}/><Filter label="priority" values={unique(vehicles,"priority")} filters={filters} setFilters={setFilters}/><select className="form-control" value={filters.maintenance} onChange={e=>setFilters({...filters,maintenance:e.target.value})}><option>All</option><option>Due</option><option>Not Due</option></select></div></section>
    <VehicleTable vehicles={filtered} selectedId={selectedId} onSelect={setSelectedId}/>
    <div className="grid gap-6 xl:grid-cols-3"><AlertsPanel alerts={openAlerts} setAlerts={setAlerts}/><Events events={events}/><Geofences geofences={mockGeofences}/></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_2fr]"><Summary vehicles={vehicles}/><Routes routes={mockRoutePerformance}/></div>
  </div></div>
}
function Filter({label,keyName,values,filters,setFilters}){const key=keyName||label;return <select className="form-control" value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option>All</option>{values.map(v=><option key={v}>{v}</option>)}</select>}
function TrackingMap({vehicles,selectedId,onSelect,showRoutes,showGeofences}){const bounds={minLat:13.70,maxLat:14.10,minLng:-61.08,maxLng:-60.86};const pos=(v)=>({left:`${((v.longitude-bounds.minLng)/(bounds.maxLng-bounds.minLng))*100}%`,top:`${(1-((v.latitude-bounds.minLat)/(bounds.maxLat-bounds.minLat)))*100}%`});return <section className="card overflow-hidden"><div className="border-b border-brand-border bg-brand-deep px-5 py-4 text-white"><h2 className="text-lg font-extrabold">Saint Lucia Live Map</h2><p className="text-sm text-white/75">OpenStreetMap-style mock layer; no GPS provider or API key required.</p></div><div className="relative h-[560px] overflow-hidden bg-[#d7e7d1]" style={{backgroundImage:"url('https://tile.openstreetmap.org/10/338/488.png')",backgroundSize:"cover",backgroundPosition:"center"}}>{showRoutes&&<svg className="absolute inset-0 h-full w-full opacity-70">{vehicles.slice(0,8).map((v,i)=><line key={v.id} x1="50%" y1="18%" x2={pos(v).left} y2={pos(v).top} stroke={i%2?"#997B20":"#0F2E66"} strokeWidth="2" strokeDasharray="6 7" />)}</svg>}{showGeofences&&["Castries Depot","Vieux Fort Zone","Rodney Bay"].map((g,i)=><div key={g} className="absolute rounded-full border-2 border-brand-gold/70 bg-brand-gold/10 px-3 py-2 text-xs font-bold text-brand-deep" style={{left:[42,69,57][i]+"%",top:[23,84,11][i]+"%"}}>{g}</div>)}{vehicles.map(v=><button key={v.id} onClick={()=>onSelect(v.id)} className={`group absolute -translate-x-1/2 -translate-y-1/2 rounded-full border-4 bg-white p-1 shadow-xl transition hover:z-20 hover:scale-110 ${selectedId===v.id?"z-20 ring-4 ring-brand-gold":""}`} style={{...pos(v),borderColor:statusColor[v.status]}} title={v.vehicleName}><span className="block h-4 w-4 rounded-full" style={{background:statusColor[v.status]}}/><div className="pointer-events-none absolute left-7 top-0 hidden w-64 rounded-xl bg-white p-3 text-left text-xs shadow-2xl group-hover:block"><b className="text-brand-deep">{v.vehicleName} • {v.plateNumber}</b><p>{v.driverName}</p><StatusBadge status={v.status}/><p className="mt-1">{v.currentLocationName} • {v.speedKmh} km/h • Fuel {v.fuelLevel}%</p><p>{v.routeName} → {v.nextStop}</p><p>ETA {v.eta} • Updated {time(v.lastUpdated)}</p><p>{v.alerts.length?`Alerts: ${v.alerts.join(", ")}`:"No active vehicle alerts"}</p><span className="mt-2 inline-block font-bold text-brand-gold">Click marker to select vehicle</span></div></button>)}</div></section>}
function DetailPanel({vehicle}){if(!vehicle)return <aside className="empty-state">Select a vehicle marker or table row to view detailed telemetry.</aside>;return <aside className="card-pad"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-extrabold text-brand-deep">{vehicle.vehicleName}</h2><p className="text-sm text-brand-slate">{vehicle.plateNumber} • {vehicle.vehicleType}</p></div><StatusBadge status={vehicle.status}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm">{[["Driver",vehicle.driverName],["Phone",vehicle.driverPhone],["Location",vehicle.currentLocationName],["Coordinates",`${vehicle.latitude}, ${vehicle.longitude}`],["Speed",`${vehicle.speedKmh} km/h`],["Fuel",`${vehicle.fuelLevel}%`],["Odometer",`${vehicle.odometerKm} km`],["Engine",vehicle.engineStatus],["Route",vehicle.routeName],["Origin",vehicle.origin],["Destination",vehicle.destination],["Next Stop",vehicle.nextStop],["ETA",vehicle.eta],["Cargo",vehicle.cargoType],["Priority",vehicle.priority],["Branch",vehicle.assignedBranch],["Deliveries",`${vehicle.completedDeliveryCount}/${vehicle.currentDeliveryCount+vehicle.completedDeliveryCount}`],["Maintenance",vehicle.maintenanceDue?"Due":"Not due"],["Updated",dateTime(vehicle.lastUpdated)],["Temp",vehicle.temperature==null?"N/A":`${vehicle.temperature} °C`]].map(([k,v])=><div key={k} className="rounded-xl bg-brand-soft p-3"><p className="text-xs font-bold uppercase text-brand-slate">{k}</p><p className="font-bold text-brand-deep">{v}</p></div>)}</div><div className="mt-4 space-y-3"><div><p className="mb-1 text-sm font-bold text-brand-deep">Trip progress {Math.round(vehicle.tripProgressPercent)}%</p><Meter value={vehicle.tripProgressPercent} tone="bg-brand-navy"/></div><div><p className="mb-1 text-sm font-bold text-brand-deep">Fuel level {vehicle.fuelLevel}%</p><Meter value={vehicle.fuelLevel}/></div></div><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-brand-tint px-3 py-1 text-sm font-bold text-brand-gold">{vehicle.priority} priority</span><span className="rounded-full bg-red-50 px-3 py-1 text-sm font-bold text-red-700">{vehicle.alerts.length} alerts</span></div>{vehicle.alerts.length>0&&<ul className="mt-3 list-disc pl-5 text-sm text-brand-slate">{vehicle.alerts.map(a=><li key={a}>{a}</li>)}</ul>}</aside>}
function VehicleTable({vehicles,selectedId,onSelect}){return <section className="table-wrap"><table className="app-table"><thead><tr>{["Vehicle","Plate","Driver","Location","Status","Speed","Fuel","ETA","Route","Alerts","Action"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{vehicles.map(v=><tr key={v.id} onClick={()=>onSelect(v.id)} className={`cursor-pointer hover:bg-brand-soft ${selectedId===v.id?"bg-brand-tint":""}`}><td className="font-bold text-brand-deep">{v.vehicleName}</td><td>{v.plateNumber}</td><td>{v.driverName}</td><td>{v.currentLocationName}</td><td><StatusBadge status={v.status}/></td><td>{v.speedKmh} km/h</td><td>{v.fuelLevel}%</td><td>{v.eta}</td><td>{v.routeName}</td><td>{v.alerts.length}</td><td><button className="btn-secondary py-1" onClick={()=>onSelect(v.id)}>Select</button></td></tr>)}</tbody></table></section>}
function AlertsPanel({alerts,setAlerts}){return <section className="card-pad"><h2 className="text-lg font-extrabold text-brand-deep">Active Fleet Alerts</h2><div className="mt-3 max-h-96 space-y-3 overflow-auto">{alerts.map(a=><div key={a.id} className="rounded-xl border border-red-100 bg-red-50 p-3"><div className="flex justify-between"><b className="text-red-800">{a.type} • {a.severity}</b><button className="text-xs font-bold text-brand-navy" onClick={()=>setAlerts(prev=>prev.map(x=>x.id===a.id?{...x,status:"Resolved"}:x))}>Dismiss</button></div><p className="text-sm text-brand-slate">{a.message}</p><p className="text-xs text-brand-slate">{a.location} • {dateTime(a.timestamp)}</p></div>)}</div></section>}
function Events({events}){return <section className="card-pad"><h2 className="text-lg font-extrabold text-brand-deep">Event Feed</h2><div className="mt-3 max-h-96 space-y-3 overflow-auto">{events.map(e=><div key={e.id} className="border-l-4 border-brand-gold bg-brand-soft p-3"><b className="text-sm text-brand-deep">{e.eventType} • {e.vehicleName}</b><p className="text-sm text-brand-slate">{e.message}</p><p className="text-xs text-brand-slate">{dateTime(e.timestamp)} • {e.severity}</p></div>)}</div></section>}
function Geofences({geofences}){return <section className="card-pad"><h2 className="text-lg font-extrabold text-brand-deep">Geofence Activity</h2><div className="mt-3 space-y-3">{geofences.map(g=><div key={g.id} className="rounded-xl bg-brand-soft p-3"><b className="text-brand-deep">{g.name}</b><p className="text-sm text-brand-slate">{g.type} • {g.vehiclesInside} inside • {g.activeAlerts} alerts</p><p className="text-xs text-brand-slate">Last activity {time(g.lastActivity)}</p></div>)}</div></section>}
function Summary({vehicles}){const lowest=[...vehicles].sort((a,b)=>a.fuelLevel-b.fuelLevel)[0];const most=[...vehicles].sort((a,b)=>b.completedDeliveryCount-a.completedDeliveryCount)[0];const due=vehicles.find(v=>v.maintenanceDue);return <section className="card-pad"><h2 className="text-lg font-extrabold text-brand-deep">Operations Summary</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{[["Top performing route",reportSummary.topRoute],["Most delayed route",reportSummary.delayedRoute],["Lowest fuel",`${lowest.vehicleName} (${lowest.fuelLevel}%)`],["Most completed stops",`${most.vehicleName} (${most.completedDeliveryCount})`],["Maintenance soon",due.vehicleName],["Km simulated today",reportSummary.totalKmToday],["Avg route completion",`${reportSummary.avgCompletion}%`],["Geofence entries",reportSummary.geofenceEntries],["Alerts resolved",reportSummary.alertsResolved]].map(([k,v])=><div key={k} className="rounded-xl bg-brand-soft p-3"><p className="text-xs font-bold uppercase text-brand-slate">{k}</p><p className="font-extrabold text-brand-deep">{v}</p></div>)}</div></section>}
function Routes({routes}){return <section className="card-pad"><h2 className="text-lg font-extrabold text-brand-deep">Route Performance</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{routes.map(r=><div key={r.id} className="rounded-xl border border-brand-border p-4"><div className="flex justify-between"><b className="text-brand-deep">{r.routeName}</b><span className="text-sm font-bold text-brand-gold">{r.delayRisk} risk</span></div><p className="text-sm text-brand-slate">{r.assignedVehicle} • {r.driver}</p><p className="text-sm text-brand-slate">{r.origin} → {r.destination}</p><p className="text-sm text-brand-slate">Stops {r.completedStops}/{r.stops} • {r.distance} km • ETA {r.eta}</p><StatusBadge status={r.status}/></div>)}</div></section>}
